#!/bin/sh

# This normalization will also run check and fix routines
psfnormalize -p checkfix=fix source/masters/ShimenkanMaster-ExtraLight.ufo -l source/logs/normXL.log
psfnormalize -p checkfix=fix source/masters/ShimenkanMaster-Black.ufo -l source/logs/normK.log
psfnormalize -p checkfix=fix source/masters/ShimenkanMaster-ExtraLightItalic.ufo -l source/logs/normXLI.log
psfnormalize -p checkfix=fix source/masters/ShimenkanMaster-BlackItalic.ufo -l source/logs/normKI.log

# psfsetpsnames -i source/glyph_data.csv source/masters/ShimenkanMaster-ExtraLight.ufo
# psfsetglyphorder --header sort_final -i source/glyph_data.csv source/ShimenkanMaster-ExtraLight.ufo

# Following sync will copy psnames and glyphorder updates to all fonts
psfsyncmasters source/ShimenkanRoman.designspace source/ShimenkanItalic.designspace  -l source/logs/sync.log
